language: rust
rust:
     - stable
     - beta
     - nightly
matrix:
        env:
                - TEST_DIR=rust/mastering-rust/03_07_bench-test
        allow_failures:
                - rust: nightly
        script: cd $TEST_DIR && cargo test
