language: rust
rust:
        #- stable
        #- beta
     - nightly
matrix:
        env:
                - TEST_DIR=rust/mastering-rust/*
                - TEST: true
                - PROD: false
        
        allow_failures:
                - rust: nightly
        script: cd $TEST_DIR 
