import turtle
turtle.shape("turtle")
turtle.color("red","green")
turtle.width(2)
turtle.forward(150)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(150)
turtle.exitonclick()
